"""Last call ts

Revision ID: 1e23308c09f2
Revises: 46ad739ace48
Create Date: 2015-03-01 13:08:14.435202

"""

# revision identifiers, used by Alembic.
revision = '1e23308c09f2'
down_revision = '46ad739ace48'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('last_phone_call_ts', sa.DateTime(), nullable=True))
    ### end Alembic commands ###



def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact', 'last_phone_call_ts')
    ### end Alembic commands ###
