"""empty message

Revision ID: 46ad739ace48
Revises: 596db1ecb6ec
Create Date: 2015-02-01 21:48:07.965456

"""

# revision identifiers, used by Alembic.
revision = '46ad739ace48'
down_revision = '596db1ecb6ec'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('enable_phone_call_warnings', sa.Boolean(), nullable=True))
    ### end Alembic commands ###
    pass

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact', 'enable_phone_call_warnings')
    ### end Alembic commands ###
    pass
