"""empty message

Revision ID: 4d7e882e5f43
Revises: None
Create Date: 2015-01-09 10:18:03.465142

"""

# revision identifiers, used by Alembic.
revision = '4d7e882e5f43'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=160), nullable=True),
    sa.Column('subject', sa.String(length=100), nullable=True),
    sa.Column('created_ts', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relay',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=40), nullable=True),
    sa.Column('switch_on_text', sa.String(length=16), nullable=True),
    sa.Column('switch_off_text', sa.String(length=16), nullable=True),
    sa.Column('arduino_pin', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('enable_sms_warnings', sa.Boolean(), nullable=True),
    sa.Column('enable_email_warnings', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensor_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit', sa.Unicode(length=5), nullable=True),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('relay_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('relay_id', sa.Integer(), nullable=True),
    sa.Column('created_ts', sa.DateTime(), nullable=True),
    sa.Column('from_state', sa.Integer(), nullable=True),
    sa.Column('to_state', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['relay_id'], ['relay.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sensor_code', sa.String(length=5), nullable=True),
    sa.Column('description', sa.String(length=40), nullable=True),
    sa.Column('save_to_rrd_db', sa.Boolean(), nullable=True),
    sa.Column('rrd_db_path', sa.String(), nullable=True),
    sa.Column('emit_every', sa.Integer(), nullable=True),
    sa.Column('max_possible_value', sa.Float(precision=2, decimal_return_scale=2), nullable=True),
    sa.Column('max_warning_value', sa.Float(precision=2, decimal_return_scale=2), nullable=True),
    sa.Column('min_possible_value', sa.Float(precision=2, decimal_return_scale=2), nullable=True),
    sa.Column('min_warning_value', sa.Float(precision=2, decimal_return_scale=2), nullable=True),
    sa.Column('observable_measurements', sa.Integer(), nullable=True),
    sa.Column('observable_alarming_measurements', sa.Integer(), nullable=True),
    sa.Column('warning_wait_minutes', sa.Integer(), nullable=True),
    sa.Column('enable_warnings', sa.Boolean(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['sensor_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensor')
    op.drop_table('relay_log')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('sensor_type')
    op.drop_table('contact')
    op.drop_table('relay')
    op.drop_table('device')
    op.drop_table('notification')
    ### end Alembic commands ###
