"""empty message

Revision ID: 596db1ecb6ec
Revises: 4d7e882e5f43
Create Date: 2015-01-11 16:45:03.269639

"""

# revision identifiers, used by Alembic.
revision = '596db1ecb6ec'
down_revision = '4d7e882e5f43'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('locale', sa.String(length=2), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'locale')
    ### end Alembic commands ###
